// All text, data and timings for Last Landing. Times are "story seconds": 1 s of story = 1 s of ?record=1
// and var(--k) of scroll (site.css). Clip positions/origins measured from the frames (site/DESIGN.md).

export type ChapterKey = "title" | "squad" | "gear" | "map" | "match" | "drop";

export type Chapter = {
  key: ChapterKey;
  n: number;
  name: string;
  frames: string; // frame folder in public/
  count: number; // frames in the folder
  play: number; // story seconds the clip scrubs for
  /** brightest point of the clip's LAST frame (0–1 of the stage): the deep transition flies out of it */
  origin: [number, number];
  /** frame shown in ?static=1 (0–1 of the clip) */
  poster: number;
};

export const T = 0.8; // deep transition, story seconds (part of the incoming chapter)
export const HERO_HOLD = 1.5; // record mode: the logo builds before the first scroll
export const END_GROW = 1.2; // white-out → end card
export const END_HOLD = 3.5; // record mode holds on the end card + credit

export const chapters: Chapter[] = [
  { key: "title", n: 1, name: "Last Landing", frames: "/frames/last-landing-ch01-title", count: 160, play: 5.2, origin: [0.45, 0.32], poster: 0.12 },
  { key: "squad", n: 2, name: "Squad", frames: "/frames/last-landing-ch02-squad", count: 160, play: 5.7, origin: [0.46, 0.36], poster: 0.45 },
  { key: "gear", n: 3, name: "Loadout", frames: "/frames/last-landing-ch03-gear", count: 160, play: 4.2, origin: [0.49, 0.22], poster: 0.55 },
  { key: "map", n: 4, name: "Drop zone", frames: "/frames/last-landing-ch04-map", count: 160, play: 4.2, origin: [0.48, 0.57], poster: 1 },
  { key: "match", n: 5, name: "Matchmaking", frames: "/frames/last-landing-ch05-matchmaking", count: 160, play: 4.2, origin: [0.52, 0.32], poster: 0.3 },
  { key: "drop", n: 6, name: "Drop", frames: "/frames/last-landing-ch06-drop", count: 120, play: 4.0, origin: [0.5, 0.5], poster: 0.2 },
];

/** Start (story s) of each chapter: its transition begins here (chapter 1 starts at 0 with no transition). */
export const starts: number[] = [];
{
  let t = 0;
  chapters.forEach((c, i) => {
    starts.push(t);
    t += (i ? T : 0) + c.play;
  });
}
export const playStart = (i: number) => starts[i] + (i ? T : 0);
export const playEnd = (i: number) => playStart(i) + chapters[i].play;
export const endStart = playEnd(chapters.length - 1);
export const storySeconds = endStart + END_GROW;

export const title = { top: "LAST", bottom: "LANDING", press: "Press to start", hint: "Scroll to deploy" };

export const squad = {
  label: "Your squad",
  players: [
    { name: "VEX", level: 42, rank: "Diamond", tone: "#7FD3FF", role: "Assault" },
    { name: "NOVA", level: 38, rank: "Platinum", tone: "#2DD4BF", role: "Scout", lead: true },
    { name: "TANK", level: 51, rank: "Master", tone: "#FF6A2B", role: "Support" },
  ],
};

export const gear = {
  label: "Loadout",
  item: "Drop kit · Mk II",
  // window = the part of the clip (0–1) while the camera passes that part
  stats: [
    { name: "Glide", part: "Wings", value: 91, window: [0.02, 0.35] as [number, number] },
    { name: "Armor", part: "Backpack", value: 82, window: [0.35, 0.65] as [number, number] },
    { name: "Speed", part: "Helmet", value: 64, window: [0.65, 0.95] as [number, number] },
  ],
};

export const map = {
  kicker: "Select landing",
  place: "Harbor Town",
  meta: "Loot · High   Risk · Medium",
  // the orange ring in ch04 (frame measurements): [clip progress, centre x, centre y, left, right, top, bottom]
  ring: [
    [0.6, 0.486, 0.494, 0.27, 0.71, 0.35, 0.63],
    [0.7, 0.481, 0.513, 0.2, 0.76, 0.33, 0.69],
    [0.8, 0.477, 0.534, 0.14, 0.82, 0.31, 0.76],
    [0.9, 0.476, 0.556, 0.09, 0.87, 0.29, 0.82],
    [1.0, 0.481, 0.569, 0.06, 0.9, 0.29, 0.85],
  ] as number[][],
};

export const match = {
  label: "Matchmaking",
  mode: "Squads · Harbor Town",
  timer: [0, 7] as [number, number], // seconds shown 0:00 → 0:07
  players: [12, 99] as [number, number],
  playersAt: 0.52, // 99 reached at the jump
  readyAt: 0.55, // the squad leaves the ramp (≈ 4.4 s of the 8 s clip)
  ready: "Ready",
};

export const drop = { word: "JUMP" };

export const end = {
  title: "LAST LANDING",
  day: "Built by Triozen Tech",
  follow: "Follow for more",
  credit: "Last Landing is an original concept, not a real game. All footage AI-generated by Triozen Tech.",
};
